CREATE TABLE user (
	id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(255) NOT NULL,
	password VARCHAR(255) NOT NULL,
	date DATETIME(2) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8;